---
DEPLOYMENT_PLAYBOOKS: https://github.com/c4coin/deployment-playbooks.git
DEPLOYMENT_TERRAFORM: https://github.com/c4coin/deployment-terraform.git
DEPLOYMENT_PLAYBOOKS_BRANCH: master
DEPLOYMENT_TERRAFORM_BRANCH: master
POA_CONSENSUS_CONTRACTS: https://github.com/c4coin/poa-network-consensus-contracts.git
POA_CONSENSUS_CONTRACTS_BRANCH: "1.0"
terraform_version: 0.11.7
node_version: 8
moc_secret_length: 20
netstat_secret_length: 20
cert_secret_length: 20
