storage_account: tfci
container: tf-ci-state
terraform_location: /usr/bin/terraform
tf_prefix: tf-
resource_group_name: tf-test-full-setup
region: East US
PUB_KEY_STORE: id_rsa.pub
ansible_user: poa
ENVIRONMENT_NAME: POA-test-network
backend: false